name: Google Cloud Auth Test

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  authenticate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: 'projects/556877521071/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'discord-bot@phd-alerts.iam.gserviceaccount.com'

      - name: Print Success Message
        run: echo "OKAY"
