name: Fetch OpEd articles

on:
  schedule:
    - cron: "30 2 * * *" # At 02:30 UTC on everyday
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  oped-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run bot-02-oped.py
        env: 
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_OPED_ID: ${{ secrets.DISCORD_OPED_ID }}
        run:
          python bot-02-oped.py

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DATA/historical_oped.json
          git diff --staged --quiet || (git commit -m "Auto update historical_oped.json" && git push) 