name: Fetch PhD Advertisement Mails

on:
  schedule:
    - cron: "30 4 */7 * *" # At 04:30 UTC on every 7th day-of-month.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  phd-alerts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run main.py
        env: 
          GMAIL_STU_TOKEN: ${{ secrets.GMAIL_STU_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORD_PHD_ID: ${{ secrets.DISCORD_PHD_ID }}
        run:
          python bot-01-phd-alerts.py