name: Fetch Gmail Labels

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Required for Workload Identity Federation

jobs:
  fetch-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: 'projects/556877521071/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'discord-bot@phd-alerts.iam.gserviceaccount.com'

      - name: Fetch Gmail Labels
        run: python list_labels.py