name: Fetch Gmail Labels

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write  # Required for Workload Identity Federation

jobs:
  fetch-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client python-dotenv

      - name: Load and use secret
        env: 
          MY_SECRET_JSON: ${{ secrets.MY_SECRET_JSON }}
        run:
          python list_labels.py